# Generated by Django 3.1.5 on 2021-01-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['is_active', '-sorting']},
        ),
    ]
